# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9196ce4819c8f68d3aeb1182223ffb9fa1d9712d58cb6d636175d3a3ca60dea7280978aa5cb252238c05ab8820c86c501d9a0f7b251f3a1bc18de35da6cf4c2f

test:
  secret_key_base: e65a358cdea0daacf7c4cec60d6b17ed27f8a4314674035dc263f06081fec04af91cf75ab6cda380cc098939ef50b9cb5136c258fe29ef2e3d157e2a82d6a819

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
